from django.urls import path, include

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("accounts/login/", views.login_view, name="login"),
    path("user/<str:profile>", views.user, name="user"),
    path("logout", views.logout_view, name="logout"),
    path("user_status", views.user_status, name="user_status"),
    path("register", views.register, name="register"),
    path("get_user_id", views.get_user_id, name="get_user_id"),
    path("user_liked", views.user_liked, name="user_liked"),
    path("in_bookshelf", views.in_bookshelf, name="in_bookshelf"),
    path("in_cart", views.in_cart, name="in_cart"),
    path("get_bookshelf", views.get_bookshelf, name="get_bookshelf"),
    path("update_bookshelf", views.update_bookshelf, name="update_bookshelf"),
    path("update_cart", views.update_cart, name="update_cart"),
    path("update_rating", views.update_rating, name="update_rating"),
    path("update_listing", views.update_listing, name="update_listing"),
    path("update_donation", views.update_donation, name="update_donation"),
    path("update_bookmark", views.update_bookmark, name="update_bookmark"),
    path("get_listing", views.get_listing, name="get_listing"),
    path("delete_listing", views.delete_listing, name="delete_listing"),
    path("random_reviews", views.random_reviews, name="random_reviews"),
    path("delete_donation", views.delete_donation, name="delete_donation"),
    path("add_credits", views.add_credits, name="add_credits"),
    path("purchase_listing", views.purchase_listing, name="purchase_listing"),
    path("manage_review", views.manage_review, name="manage_review"),
    path(
        "manage_admin_donation",
        views.manage_admin_donation,
        name="manage_admin_donation",
    ),
    path("update_like", views.update_like, name="update_like"),
    path("delete_review", views.delete_review, name="delete_review"),
    path("get_user_rating", views.get_user_rating, name="get_user_rating"),
    path("get_user_credits", views.get_user_credits, name="get_user_credits"),
    path("get_book_rating", views.get_book_rating, name="get_book_rating"),
    path("get_book_reviews", views.get_book_reviews, name="get_book_reviews"),
    path("get_user_reviews", views.get_user_reviews, name="get_user_reviews"),
    path("get_user_invoices", views.get_user_invoices, name="get_user_invoices"),
    path("get_review_likes", views.get_review_likes, name="get_review_likes"),
    path("get_quote", views.get_quote, name="get_quote"),
    path("update_quote", views.update_quote, name="update_quote"),
    path("delete_quote", views.delete_quote, name="delete_quote"),
    path("user_exists", views.user_exists, name="user_exists"),
    path("load_listings", views.load_listings, name="load_listings"),
    path("user_activity_info", views.user_activity_info, name="user_activity_info"),
    path("load_bookmarks", views.load_bookmarks, name="load_bookmarks"),
    path("load_cart", views.load_cart, name="load_cart"),
    path("load_donations", views.load_donations, name="load_donations"),
    path("user_bookmarked", views.user_bookmarked, name="user_bookmarked"),
    path(
        "load_admin_donations", views.load_admin_donations, name="load_admin_donations"
    ),
    path("codex/", views.codex, name="codex"),
    path("codex/<int:isbn>", views.codex, name="book_result_isbn"),
    path("codex/<int:isbn>/<int:sale>", views.codex, name="book_sell_isbn"),
    path("codex/book_results", views.book_results, name="book_results"),
    path("book_result", views.book_result, name="book_result"),
    path("book_crate/", views.book_crate, name="book_crate"),
    path("readers_grove/", views.readers_grove, name="readers_grove"),
]
