# Generated by Django 5.0.6 on 2025-06-07 15:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_listing_timestamp_alter_bookshelf_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="listing_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.listing",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 7, 21, 4, 39, 558874)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 7, 21, 4, 39, 558874)
            ),
        ),
    ]
