# Generated by Django 5.0.6 on 2025-06-08 06:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_cart_timestamp_alter_bookshelf_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookshelf",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 8, 11, 45, 51, 590565)
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 8, 11, 45, 51, 590565)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 8, 11, 45, 51, 590565)
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("book_isbn", models.CharField(max_length=13)),
                ("transaction_amount", models.IntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("sale", "sale"), ("purchase", "purchase")],
                        max_length=8,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 6, 8, 11, 45, 51, 590565)
                    ),
                ),
                (
                    "listing_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.listing"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
