# Generated by Django 5.0.6 on 2025-06-08 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_bookshelf_timestamp_alter_cart_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 8, 12, 4, 49, 677041)
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 8, 12, 4, 49, 677041)
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 8, 12, 4, 49, 677041)
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="transaction_amount",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="listing",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 8, 12, 4, 49, 677041)
            ),
        ),
    ]
