# Generated by Django 5.0.6 on 2025-06-09 06:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_invoice_quantity_alter_bookshelf_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookshelf",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 9, 12, 7, 49, 538922)
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 9, 12, 7, 49, 531101)
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 9, 12, 7, 49, 531101)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 9, 12, 7, 49, 531101)
            ),
        ),
        migrations.CreateModel(
            name="Donate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("book_isbn", models.CharField(max_length=13)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 6, 9, 12, 7, 49, 531101)
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
