# Generated by Django 5.0.6 on 2025-06-09 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_bookshelf_timestamp_alter_cart_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="listing_id",
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 9, 19, 53, 35, 47795)
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 9, 19, 53, 35, 47795)
            ),
        ),
        migrations.AlterField(
            model_name="donate",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 9, 19, 53, 35, 47795)
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 9, 19, 53, 35, 47795)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 9, 19, 53, 35, 47795)
            ),
        ),
    ]
