# Generated by Django 5.0.6 on 2025-06-10 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_bookshelf_timestamp_alter_cart_timestamp_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmark",
            old_name="profile_id",
            new_name="bookmark_id",
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 10, 11, 18, 14, 637568)
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 10, 11, 18, 14, 637568)
            ),
        ),
        migrations.AlterField(
            model_name="donate",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 10, 11, 18, 14, 637568)
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 10, 11, 18, 14, 637568)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 10, 11, 18, 14, 637568)
            ),
        ),
    ]
