# Generated by Django 5.0.6 on 2025-06-11 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_bookshelf_book_isbn_alter_bookshelf_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="quote",
            field=models.CharField(blank=True, default="", max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 11, 18, 4, 0, 442305)
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 11, 18, 4, 0, 442305)
            ),
        ),
        migrations.AlterField(
            model_name="donate",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 11, 18, 4, 0, 442305)
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 11, 18, 4, 0, 442305)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 11, 18, 4, 0, 442305)
            ),
        ),
    ]
