# Generated by Django 5.0.6 on 2025-06-12 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_user_quote_alter_bookshelf_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="author",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="publisher",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="title",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookshelf",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 12, 13, 1, 50, 568269)
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 12, 13, 1, 50, 568269)
            ),
        ),
        migrations.AlterField(
            model_name="donate",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 12, 13, 1, 50, 568269)
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 12, 13, 1, 50, 568269)
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 12, 13, 1, 50, 568269)
            ),
        ),
    ]
