# Generated by Django 5.2.1 on 2025-06-17 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_listing_author_listing_publisher_listing_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookshelf",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 17, 13, 55, 43, 417688, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 17, 13, 55, 43, 416626, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="donate",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 17, 13, 55, 43, 416973, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 17, 13, 55, 43, 417323, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 17, 13, 55, 43, 416095, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
